FROM registry.access.redhat.com/ubi9/ubi-minimal:latest
RUN microdnf install -y util-linux-core && microdnf clean all
COPY rpms/kpatch-0.9.7-3.el9_6.noarch.rpm /opt/rpms/
COPY rpms/kpatch-patch-5_14_0-570_94_1-1-2.el9_6.x86_64.rpm /opt/rpms/
COPY entrypoint-kpatch.sh /opt/entrypoint.sh
RUN chmod +x /opt/entrypoint.sh
ENTRYPOINT ["/opt/entrypoint.sh"]
