apiVersion: v1
kind: Namespace
metadata:
  name: kpatch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kpatch
  namespace: kpatch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kpatch-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:openshift:scc:privileged
subjects:
- kind: ServiceAccount
  name: kpatch
  namespace: kpatch
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kpatch
  namespace: kpatch
spec:
  selector:
    matchLabels:
      app: kpatch
  template:
    metadata:
      labels:
        app: kpatch
    spec:
      hostPID: true
      serviceAccountName: kpatch
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      tolerations:
      - operator: Exists
      containers:
      - name: kpatch
        image: quay.io/sdodsonrht/kpatch-5.14.0-570.94.1.el9_6.x86_64:latest
        securityContext:
          privileged: true
        volumeMounts:
        - name: host
          mountPath: /host
      volumes:
      - name: host
        hostPath:
          path: /
